version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - yarn config set cache-folder .yarn
  build:
    commands:
      - yarn install
      - yarn run build
  post_build:
    commands:
      - node scripts/deploy 
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    website:
      base-directory: out
cache:
  paths:
    - .yarn/**/*
    - .cache/**/*
    - out/**/*
    - node_modules/**/*
