import { Metadata } from "next";
import { ReactNode } from "react";

import "../../styles/index.css";

type Props = {
  children: ReactNode;
  params: { locale: string };
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  return (
    <html lang={params.locale}>
      <body className="bg-gray-100" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
